apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{include "podinfo-chart.fullname" .}}
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      {{- include "podinfo-chart.selectorLabels" . | nindent 6}}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s