apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/twinkelbauer/gitops-tryout.git
    targetRevision: main
    path: charts/podinfo-chart
    helm:
      valueFiles:
        - values-dev.yaml
      values: |
        replicaCount: 2
        ui:
          color: "#34577c"
          message: "hello from dev"

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true        # löscht, was aus Git verschwindet
      selfHeal: true     # dreht manuelle Änderungen am Cluster zurück
    syncOptions:
      - CreateNamespace=true